In [2]:
import torch

In [3]:
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("You are using CPU.")

GPU is available
using GPU: NVIDIA GeForce RTX 3060


## Creating a tensor

In [5]:
# Using empty
a = torch.empty(2, 3) # shows locations value; not create value itself
print(a)

tensor([[2.2421e-44, 0.0000e+00, 4.6522e+10],
        [3.3659e-41, 1.5638e-42, 0.0000e+00]])


In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# Using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# Using rand
torch.rand(2, 3)

tensor([[0.3528, 0.5695, 0.7822],
        [0.3396, 0.9665, 0.1325]])

In [10]:
# Use of seed
torch.rand(2, 3)

tensor([[0.5714, 0.1243, 0.7985],
        [0.4020, 0.5109, 0.3027]])

In [11]:
# manual_seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# Using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# Other ways

# arange
print(f"Using range -> {torch.arange(0, 10)}")

# arange with steps
print(f"Using range -> {torch.arange(0, 10, 2)}")

# using linspace
print(f"Using linspace -> {torch.linspace(0, 10, 10)}") # evenly spaced value create with torch

# using eye
print(f"Using eye -> {torch.eye(5)}") # identity matrix

# using full
print(f"Using full -> {torch.full((3, 3), 5)}")

Using range -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using range -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
# same shape another tensor
torch.empty_like(x)

tensor([[3616445622929465956, 6067528668160208181, 4049644494347974193],
        [6501286048250999854, 7309453675965983778, 8315168162784306286]])

In [18]:
# same shape another tensor
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

## Tensor Data Types

In [21]:
# Find data type
x.dtype

torch.int64

In [22]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# using to() => change existing data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

### 1. Scalar operation

In [28]:
x = torch.tensor([[1, 2], [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

In [29]:
# Addition
x + 2

tensor([[3, 4],
        [5, 6]])

In [30]:
# Subtraction
x - 2

tensor([[-1,  0],
        [ 1,  2]])

In [31]:
# multiplication
x * 2

tensor([[2, 4],
        [6, 8]])

In [32]:
# divition
x / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [33]:
# int division
(x * 100) // 3

tensor([[ 33,  66],
        [100, 133]])

In [34]:
# mod
((x * 100) // 3) % 2

tensor([[1, 0],
        [0, 1]])

In [35]:
# power
x ** 2

tensor([[ 1,  4],
        [ 9, 16]])

### 2. Element wise operation

In [36]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [37]:
# add
a + b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [38]:
# sub
a - b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [39]:
# multiplication
a * b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [40]:
# divition
a / b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [41]:
# power
a * b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [43]:
# mod
a % b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [44]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [45]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [46]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [47]:
d = torch.tensor([1.9, 2.3, 3.5, 4.6])
d

tensor([1.9000, 2.3000, 3.5000, 4.6000])

In [48]:
# round
torch.round(d)

tensor([2., 2., 4., 5.])

In [49]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [50]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [51]:
# clamp --> number will be in a particular range
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation
* Reduce whole tensors to a single number

In [61]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [62]:
# sum
torch.sum(e)

tensor(42.)

In [63]:
# sum along columns
torch.sum(e, dim=0)

tensor([14., 16., 12.])

In [64]:
# sum along rows
torch.sum(e, dim=1)

tensor([17., 25.])

In [65]:
# mean
torch.mean(e)

tensor(7.)

In [66]:
# mean along col
torch.mean(e, dim=0, )

tensor([7., 8., 6.])

In [67]:
# median
torch.median(e)

tensor(7.)

In [68]:
# max and min
torch.max(e)

tensor(9.)

In [69]:
torch.min(e)

tensor(5.)

In [70]:
# product
torch.prod(e)

tensor(99225.)

In [71]:
# standard deviation
torch.std(e)

tensor(1.7889)

In [72]:
# variance
torch.var(e)

tensor(3.2000)

In [75]:
# argmax -> position of maximum item
torch.argmax(e)

tensor(3)

In [76]:
# argmin -> position of minimum item
torch.argmin(e)

tensor(0)

### 4. Matrix operation

In [79]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)
print(f)
print(g)

tensor([[6, 1, 5],
        [5, 0, 4]])
tensor([[3, 8],
        [8, 3],
        [3, 5]])


In [81]:
# matrix multiplication
torch.matmul(f, g)

tensor([[41, 76],
        [27, 60]])

In [83]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
print(vector1)
print(vector2)

tensor([1, 2])
tensor([3, 4])


In [84]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [85]:
print(f)

tensor([[6, 1, 5],
        [5, 0, 4]])


In [86]:
# transpose
torch.transpose(f, 0, 1)

tensor([[6, 5],
        [1, 0],
        [5, 4]])

In [87]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 6., 4.],
        [0., 8., 4.],
        [7., 2., 3.]])

In [88]:
# determinant
torch.det(h)

tensor(-56.0000)

In [89]:
# inverse
torch.inverse(h)

tensor([[-0.2857,  0.1786,  0.1429],
        [-0.5000,  0.5000,  0.0000],
        [ 1.0000, -0.7500,  0.0000]])

### 5. Comparison operations

In [91]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)
print(i)
print(j)

tensor([[5, 4, 4],
        [1, 1, 2]])
tensor([[4, 7, 2],
        [5, 6, 1]])


In [92]:
# grater than
i > j

tensor([[ True, False,  True],
        [False, False,  True]])

In [93]:
# less than
i < j

tensor([[False,  True, False],
        [ True,  True, False]])

In [94]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [95]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [96]:
# greater than equal to 
i >= j

tensor([[ True, False,  True],
        [False, False,  True]])

In [97]:
# less than equal to
i <= j

tensor([[False,  True, False],
        [ True,  True, False]])

### 6. Special functions

In [98]:
k = torch.randint(size=(2, 3), low=0, high=10)
k

tensor([[4, 5, 6],
        [9, 2, 3]])

In [99]:
# log
torch.log(k)

tensor([[1.3863, 1.6094, 1.7918],
        [2.1972, 0.6931, 1.0986]])

In [100]:
# exp
torch.exp(k)

tensor([[5.4598e+01, 1.4841e+02, 4.0343e+02],
        [8.1031e+03, 7.3891e+00, 2.0086e+01]])

In [101]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 2.2361, 2.4495],
        [3.0000, 1.4142, 1.7321]])

In [102]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9933, 0.9975],
        [0.9999, 0.8808, 0.9526]])

In [103]:
# softmax
torch.softmax(k, dim=0, dtype=torch.float32)

tensor([[0.0067, 0.9526, 0.9526],
        [0.9933, 0.0474, 0.0474]])

In [104]:
# relu
torch.relu(k)

tensor([[4, 5, 6],
        [9, 2, 3]])

## Inplace Operations
* add underscore(_) of every functions

In [105]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)
print(m)
print(n)

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])


In [106]:
m + n

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [107]:
m.add_(n)

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [108]:
m

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [109]:
n

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [110]:
torch.relu(m)

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [111]:
m.relu_()

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

## Copying a tensor

In [112]:
a = torch.rand(2, 3)
a

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [113]:
b = a

In [114]:
b

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [115]:
a[0][0] = 0

In [116]:
a

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [117]:
b

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [118]:
id(a)

131007453553952

In [119]:
id(b)

131007453553952

In [120]:
b = a.clone()
b

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [121]:
a[0][0] = 10
a

tensor([[10.0000,  0.7582,  0.6688],
        [ 0.2651,  0.2336,  0.5057]])

In [122]:
b

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [123]:
id(a)

131007453553952

In [124]:
id(b)

131007507916704

## Tensor Operations on GPU

In [125]:
torch.cuda.is_available()

True

In [126]:
device = torch.device('cuda')
device

device(type='cuda')

In [127]:
# create a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [130]:
# moving an existing tensor to GPU
print(a)

b = a.to(device)

tensor([[10.0000,  0.7582,  0.6688],
        [ 0.2651,  0.2336,  0.5057]])


In [131]:
b

tensor([[10.0000,  0.7582,  0.6688],
        [ 0.2651,  0.2336,  0.5057]], device='cuda:0')

In [132]:
b + 5

tensor([[15.0000,  5.7582,  5.6688],
        [ 5.2651,  5.2336,  5.5057]], device='cuda:0')

In [136]:
import time

# Define the size of the matrices
size=10000 # large size for performance comparison

# create random matrices on cpu
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# measure time on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time: .4f} seconds")

# move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time: .4f} seconds")

# compare results
print(f"\nSpeedup (CPU time / GPU time): {cpu_time / gpu_time}")

Time on CPU:  1.6149 seconds
Time on GPU:  0.2280 seconds

Speedup (CPU time / GPU time): 7.082038413684222


## Reshaping Tensors

In [138]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [139]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [140]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [141]:
b = torch.rand(2,3,4)
b

tensor([[[0.1476, 0.2081, 0.5330, 0.3768],
         [0.2254, 0.6387, 0.1616, 0.4012],
         [0.5106, 0.3696, 0.6231, 0.1191]],

        [[0.1854, 0.0566, 0.5113, 0.8340],
         [0.3405, 0.8644, 0.9594, 0.7425],
         [0.7045, 0.1476, 0.1044, 0.9013]]])

In [ ]:
# permute (shape)
b.permute(2, 0, 1)
b

tensor([[[0.1476, 0.2081, 0.5330, 0.3768],
         [0.2254, 0.6387, 0.1616, 0.4012],
         [0.5106, 0.3696, 0.6231, 0.1191]],

        [[0.1854, 0.0566, 0.5113, 0.8340],
         [0.3405, 0.8644, 0.9594, 0.7425],
         [0.7045, 0.1476, 0.1044, 0.9013]]])

In [144]:
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [146]:
# unsqeeze (on position)
c = torch.rand(226, 226, 3)
print(c.unsqueeze(0).shape)
print(c.unsqueeze(1).shape)
print(c.unsqueeze(2).shape)

torch.Size([1, 226, 226, 3])
torch.Size([226, 1, 226, 3])
torch.Size([226, 226, 1, 3])


In [149]:
# squeeze
d = torch.rand(1, 20)
d.shape

torch.Size([1, 20])

In [150]:
d.squeeze(0).shape

torch.Size([20])

## Numpy and PyTorch

In [151]:
import numpy as np

In [152]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [154]:
b = a.numpy()
type(b)

numpy.ndarray

In [155]:
c = np.array([1, 2, 3])
type(c)

numpy.ndarray

In [158]:
torch.from_numpy(c)

tensor([1, 2, 3])