In [61]:
import numpy as np
import pandas as pd
import torch 
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [62]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [63]:
df.shape

(569, 33)

In [64]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [65]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [66]:
df.shape

(569, 31)

In [67]:
X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

In [68]:
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

## Train test split

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Scaling

In [70]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [71]:
X_train

array([[-1.15036482, -0.39064196, -1.12855021, ..., -0.75798367,
        -0.01614761, -0.38503402],
       [-0.93798972,  0.68051405, -0.94820146, ..., -0.60687023,
         0.09669004, -0.38615797],
       [ 0.574121  , -1.03333557,  0.51394098, ..., -0.02371948,
        -0.20050207, -0.75144254],
       ...,
       [-1.32422924, -0.20048168, -1.31754581, ..., -0.97974953,
        -0.71542314, -0.11978123],
       [-1.24380987, -0.2245526 , -1.28007609, ..., -1.75401433,
        -1.58157125, -1.00601779],
       [-0.73694129,  1.14989702, -0.71226578, ..., -0.27460457,
        -1.25895095,  0.21515662]], shape=(455, 30))

In [72]:
y_train

338    B
427    B
406    B
96     B
490    B
      ..
277    M
9      M
359    B
192    B
559    B
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [73]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [74]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,

## Numpy arrays to PyTorch tensors

In [75]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [76]:
X_train_tensor.shape

torch.Size([455, 30])

In [77]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [78]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

## Important Parameters

In [79]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [80]:
# Create Model
model = Model(X_train_tensor.shape[1])
model(X_train_tensor.float())

tensor([[0.3984],
        [0.4124],
        [0.3739],
        [0.3979],
        [0.3952],
        [0.3696],
        [0.3696],
        [0.3696],
        [0.5053],
        [0.3701],
        [0.4164],
        [0.3696],
        [0.3696],
        [0.3696],
        [0.3696],
        [0.3696],
        [0.3740],
        [0.3696],
        [0.3696],
        [0.4315],
        [0.4754],
        [0.3696],
        [0.4090],
        [0.4051],
        [0.4187],
        [0.4049],
        [0.3712],
        [0.3696],
        [0.4034],
        [0.3702],
        [0.3735],
        [0.4725],
        [0.3936],
        [0.3981],
        [0.3721],
        [0.3731],
        [0.3751],
        [0.4492],
        [0.4358],
        [0.3810],
        [0.3696],
        [0.4028],
        [0.3696],
        [0.4353],
        [0.3696],
        [0.3952],
        [0.4384],
        [0.3697],
        [0.3814],
        [0.3899],
        [0.3744],
        [0.3823],
        [0.4180],
        [0.3804],
        [0.3781],
        [0

In [81]:
model.linear1.weight

Parameter containing:
tensor([[-3.5940e-02,  6.3501e-03,  1.2422e-01, -5.8634e-02,  9.4754e-02,
          7.2886e-02, -1.7669e-01, -2.2042e-02,  8.6926e-02,  6.6140e-02,
          3.2733e-02,  1.5012e-01,  7.9450e-02,  9.4251e-02, -1.3016e-01,
         -5.6477e-02,  1.3971e-01, -1.0875e-01, -7.0234e-02, -1.4360e-01,
         -1.0747e-01,  1.5050e-01,  9.1370e-03, -6.2211e-02, -1.8008e-01,
          7.0881e-02,  1.6059e-01, -2.7835e-02, -2.4728e-02,  2.9084e-02],
        [ 8.8436e-02,  9.6830e-02,  8.4485e-03, -3.7875e-03,  5.9620e-02,
         -4.7343e-02, -7.8170e-02,  1.4936e-01, -8.1563e-02,  1.6260e-01,
         -1.2713e-02,  3.4921e-02,  1.5087e-01, -9.0218e-02, -6.6837e-02,
         -2.8374e-03, -1.0745e-02,  6.5546e-02, -1.8260e-03,  1.5021e-01,
         -1.5885e-02,  9.7971e-02, -1.1006e-01,  7.9177e-02, -1.5984e-01,
          9.4726e-02, -1.4826e-01, -1.0583e-01, -8.8698e-02,  1.8120e-01],
        [-1.7375e-02,  8.6019e-03,  1.6166e-01,  1.3808e-01,  3.6127e-02,
         -1.81

In [82]:
model.linear1.bias

Parameter containing:
tensor([ 0.0074, -0.0945,  0.0974], requires_grad=True)

## Visualize

In [83]:
# pip install torchinfo
from torchinfo import summary

In [84]:
summary(model, input_size=(X_train_tensor.shape[1],))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [1]                       --
├─Linear: 1-1                            [3]                       93
├─ReLU: 1-2                              [3]                       --
├─Linear: 1-3                            [1]                       4
├─Sigmoid: 1-4                           [1]                       --
Total params: 97
Trainable params: 97
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Using Sequential Container

In [85]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 32),
            nn.ReLU(),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )
    
    def forward(self, features):
        out = self.network(features)
        return out

## Important Parameters

In [86]:
learning_rate = 0.1
epochs = 25

In [92]:
# define loss function
loss_function = nn.BCELoss()
type(loss_function)

torch.nn.modules.loss.BCELoss

In [93]:
model = Model(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
type(optimizer)

for epoch in range(epochs):
    # Forward pass
    y_pred = model(X_train_tensor.float())
    
    # Loss
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1).float()) # we can also use reshape here.
    
    # clear the gradients
    optimizer.zero_grad()
    
    # Backward pass
    loss.backward()
    
    # Update weights
    # with torch.no_grad():
    #     for param in model.parameters():
    #         param -= learning_rate * param.grad
    
    # # Zero gradients
    # model.zero_grad()
    
    # If we use opim class for the optimizer, we can use the following code
    optimizer.step()
    # optimizer.zero_grad() # it is suggested that, we should zero the gradients before the backward pass section.


    # Print loss
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.7685484290122986
Epoch 2, Loss: 0.7279528379440308
Epoch 3, Loss: 0.6936642527580261
Epoch 4, Loss: 0.663674533367157
Epoch 5, Loss: 0.6365150809288025
Epoch 6, Loss: 0.6114072203636169
Epoch 7, Loss: 0.5879034399986267
Epoch 8, Loss: 0.5653771162033081
Epoch 9, Loss: 0.5437705516815186
Epoch 10, Loss: 0.522907555103302
Epoch 11, Loss: 0.5026175379753113
Epoch 12, Loss: 0.48291173577308655
Epoch 13, Loss: 0.4637742340564728
Epoch 14, Loss: 0.44521400332450867
Epoch 15, Loss: 0.42724040150642395
Epoch 16, Loss: 0.4099330008029938
Epoch 17, Loss: 0.3933529257774353
Epoch 18, Loss: 0.37750425934791565
Epoch 19, Loss: 0.36243879795074463
Epoch 20, Loss: 0.34816643595695496
Epoch 21, Loss: 0.3346407413482666
Epoch 22, Loss: 0.32187557220458984
Epoch 23, Loss: 0.3098810315132141
Epoch 24, Loss: 0.29862889647483826
Epoch 25, Loss: 0.28806790709495544


## Evaluation

In [94]:
# Model Evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor.float())
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5215451121330261
